# Generated by Django 3.2.5 on 2021-09-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_movie', models.CharField(max_length=45)),
                ('genero_movie', models.CharField(max_length=45)),
                ('year_movie', models.PositiveIntegerField()),
            ],
        ),
    ]
